import './categories/categories.cy'
import './groups/groups.cy'
import './items/items.cy'
import './allergens/allergens.cy'
import './select-collections/select-collections.cy'
import './select/select.cy'
import './topping-collections/topping-collections.cy'
import './topping/topping.cy'