import './load-menu/load-menu.cy'
import './load-menu/show-item-group-details.cy'
import './make-order/prepare-make-order.cy'
import './make-order/prepare-modify-make-order.cy'
import './prepare-cart/prepare-cart.cy'
import './order-status/order-status.cy'